#
# Load Balancer • Bungeecord Edition v${version}
#
# Made with <3 by LoRy24
#
settings:

  #
  # The plugin only supports Lobbies load-balancer. In the future it will also support multi servers
  # load balancers. The value of this key is an array of yml sections, that represents the host and the port of each
  # *LoadBalancer Server*. The port and the host of every server is set in the config of the LoadBalancer Spigot
  # plugin.
  #
  lobbies:
    - host: "localhost"
      port: 45623
      inProxyConfigName: "lobby1"

  #
  # The message that will be displayed when all the lobbies servers are offline
  #
  allLobbiesOfflineMessage: "&cAll the lobbies are unreachable at the moment! Please try again later."

  #
  # The hub command message
  #
  hubCommandMessage: "&aTeleporting to hub server..."