#
# Load Balancer • Spigot Edition v${version}
#
# Made with <3 by LoRy24
#
Settings:

  #
  # The host where to bind the server
  #
  Host: "localhost"

  #
  # The port of the infos server
  #
  Port: 45623


